import json
import pandas as pd
from typing import List, Dict, Any

class IngestionEngine:
    def __init__(self):
        pass

    def ingest_mock_data(self, file_path: str) -> Dict[str, Any]:
        """
        Reads the Mock JSON format generated by generate_data.py
        Returns a dictionary with 'nodes' (employees) and 'edges' (interactions)
        """
        print(f"Ingesting data from {file_path}...")
        try:
            with open(file_path, 'r') as f:
                data = json.load(f)
            
            employees = data.get('employees', [])
            raw_interactions = data.get('interactions', [])
            
            print(f"  Found {len(employees)} employees and {len(raw_interactions)} raw interaction events.")
            return data
            
        except FileNotFoundError:
            print(f"Error: File {file_path} not found.")
            return {'employees': [], 'interactions': []}
            
if __name__ == "__main__":
    # Test
    engine = IngestionEngine()
    engine.ingest_mock_data("data/digital_footprint.json")
