import { AppSettings } from '../types/settings.types';

export const DEFAULT_SETTINGS: AppSettings = {
  general: {
    language: 'en',
    autoSave: 'afterDelay',
    autoSaveDelay: 1000,
    telemetryEnabled: false,
    confirmDelete: true,
    openFolderInNewWindow: false,
  },
  editor: {
    fontSize: 14,
    fontFamily: '"JetBrains Mono", "Fira Code", "Cascadia Code", Menlo, Monaco, monospace',
    tabSize: 2,
    insertSpaces: true,
    wordWrap: 'on',
    lineNumbers: 'on',
    minimap: true,
    bracketPairColorization: true,
    autoClosingBrackets: true,
    formatOnSave: true,
    formatOnPaste: false,
    renderWhitespace: 'boundary',
    cursorBlinking: 'smooth',
    cursorStyle: 'line',
    smoothScrolling: true,
  },
  terminal: {
    defaultShell: '',
    fontSize: 14,
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    cursorBlink: true,
    cursorStyle: 'bar',
    scrollback: 10000,
    copyOnSelect: false,
  },
  ai: {
    defaultProvider: 'anthropic',
    defaultModel: 'claude-sonnet-4-20250514',
    temperature: 0.7,
    maxTokens: 4096,
    streamResponses: true,
    enableCompletion: true,
    completionDelay: 500,
    apiKeys: {},
  },
  appearance: {
    theme: 'dark-nexus',
    iconTheme: 'nexus-icons',
    fontSize: 13,
    fontFamily: 'Inter, system-ui, sans-serif',
    sidebarPosition: 'left',
    activityBarVisible: true,
    statusBarVisible: true,
    minimap: true,
  },
  keybindings: [],
};
