import { KeyBinding } from '../types/settings.types';

export const DEFAULT_KEYBINDINGS: KeyBinding[] = [
  { command: 'commandPalette', key: 'Ctrl+Shift+P', description: 'Open Command Palette' },
  { command: 'quickOpen', key: 'Ctrl+P', description: 'Quick Open File' },
  { command: 'newFile', key: 'Ctrl+N', description: 'New File' },
  { command: 'openFile', key: 'Ctrl+O', description: 'Open File' },
  { command: 'save', key: 'Ctrl+S', description: 'Save' },
  { command: 'saveAll', key: 'Ctrl+Shift+S', description: 'Save All' },
  { command: 'closeTab', key: 'Ctrl+W', description: 'Close Tab' },
  { command: 'closeAllTabs', key: 'Ctrl+K Ctrl+W', description: 'Close All Tabs' },
  { command: 'undo', key: 'Ctrl+Z', description: 'Undo' },
  { command: 'redo', key: 'Ctrl+Shift+Z', description: 'Redo' },
  { command: 'find', key: 'Ctrl+F', description: 'Find' },
  { command: 'replace', key: 'Ctrl+H', description: 'Find and Replace' },
  { command: 'findInFiles', key: 'Ctrl+Shift+F', description: 'Search in Files' },
  { command: 'toggleTerminal', key: 'Ctrl+`', description: 'Toggle Terminal' },
  { command: 'newTerminal', key: 'Ctrl+Shift+`', description: 'New Terminal' },
  { command: 'toggleSidebar', key: 'Ctrl+B', description: 'Toggle Sidebar' },
  { command: 'toggleAIPanel', key: 'Ctrl+Shift+I', description: 'Toggle AI Panel' },
  { command: 'goToLine', key: 'Ctrl+G', description: 'Go to Line' },
  { command: 'goToSymbol', key: 'Ctrl+Shift+O', description: 'Go to Symbol' },
  { command: 'formatDocument', key: 'Shift+Alt+F', description: 'Format Document' },
  { command: 'toggleComment', key: 'Ctrl+/', description: 'Toggle Comment' },
  { command: 'splitEditor', key: 'Ctrl+\\', description: 'Split Editor' },
  { command: 'zoomIn', key: 'Ctrl+=', description: 'Zoom In' },
  { command: 'zoomOut', key: 'Ctrl+-', description: 'Zoom Out' },
  { command: 'resetZoom', key: 'Ctrl+0', description: 'Reset Zoom' },
];
